// Strings comuns PT-BR (§9.6 — sem lib de i18n; literais centralizados).
export const strings = {
  appName: 'AuditView',
  appTagline: 'Auditoria contábil visual',
  common: {
    retry: 'Tentar novamente',
    cancel: 'Cancelar',
    save: 'Salvar',
    saving: 'Salvando…',
    saved: 'Salvo',
    loading: 'Carregando…',
    remove: 'Remover',
    edit: 'Editar',
    create: 'Criar',
    search: 'Buscar',
    clearFilters: 'Limpar filtros',
    back: 'Voltar',
    confirm: 'Confirmar',
  },
  auth: {
    signInTitle: 'Entrar',
    signInSubtitle: 'Acesse com seu e-mail e senha.',
    email: 'E-mail',
    password: 'Senha',
    signIn: 'Entrar',
    forgot: 'Esqueci minha senha',
    forgotTitle: 'Recuperar senha',
    forgotSubtitle: 'Enviaremos um link para redefinir sua senha.',
    sendLink: 'Enviar link',
    acceptTitle: 'Definir sua senha',
    acceptSubtitle: 'Crie uma senha para acessar o AuditView.',
    setPassword: 'Definir senha e entrar',
    invalidCredentials: 'E-mail ou senha incorretos.',
    signedOut: 'Sessão encerrada.',
    genericError: 'Não foi possível concluir. Tente novamente.',
  },
  nav: {
    overview: 'Início',
    clients: 'Clientes',
    audits: 'Auditorias',
    team: 'Equipe',
    billing: 'Faturamento',
    settings: 'Configurações',
  },
  clients: {
    title: 'Clientes',
    new: 'Novo cliente',
    emptyTitle: 'Seus clientes vão aparecer aqui.',
    emptyHint:
      'Toda auditoria pertence a um cliente do escritório — cadastre o primeiro.',
    emptyFiltered: 'Nenhum cliente corresponde aos filtros.',
    name: 'Nome',
    cnpj: 'CPF / CNPJ',
    email: 'E-mail de contato',
    situation: 'Situação',
    active: 'Ativo',
    inactive: 'Inativo',
    created: 'Cliente cadastrado.',
    updated: 'Cliente atualizado.',
    removed: 'Cliente removido.',
    deleteTitle: 'Remover cliente?',
    deleteBody:
      'As auditorias deste cliente também deixarão de aparecer. Esta ação não pode ser desfeita.',
  },
} as const
